### ISSUE TITLE
Observer Items Don't Work

### ISSUE THREAD

**Issue by tylerCain** [EquinoxRealms/Issues#1]
Wrong items, compass doesn't tp, etc.

**Comment by Kyoal** [comment]
In addition, the compass sometimes works but not always. Also after the game ends, the compass is whatever your item in the first slot of your hotbar was, until you right click slot 1. If you were playing and the game finished, you may have another item (which was in your hotbar) from the game in your hotbar until you right click it (does not have too much of an effect).

**Comment by Kyoal** [comment]
The compass works every time now. When leaving the game, while the match is in progress, you only have the compass and helmet in your inventory, which is good. 
After the game ends, you have a compass in your inventory (good). However, there's still a book and shears when the map restarts (before the game has started).
     When the map restarts, the helmet doesn't work immediately because it acts as your wearing the helmet. Once you've re-logged, the helmet will work every time. If you did not join the game at all and right clicked the helmet, the helmet will be on your head when the game finishes and you are able to put it in your inventory. This will allow you to right click it and give you the option to join a team, but will not work due to the game being finished.

**Comment by Kyoal** [comment]
There's no helmet in the observers items. Could just be me...

**Comment by Kyoal** [comment]
Helmet and compass are now fixed.

**Comment by tylerCain** [comment]
Fixed
