### ISSUE TITLE
Wool touches

### ISSUE THREAD

**Issue by Kyoal** [EquinoxRealms/Issues#3]
If a team touches a wool, the touch does not appear on the scoreboard for your own team or the observers. The wool touch message appears for your own team, but not for the observers.

**Comment by tylerCain** [comment]
Fixed for CTW. Need to test for DTM and DTC.

**Comment by Kyoal** [comment]
Wool touches show for observers on scoreboard. However there is no wool touch message for observers in chat.

**Comment by Kyoal** [comment]
Fixed!
