### ISSUE TITLE
Game over message

### ISSUE THREAD

**Issue by Kyoal** [EquinoxRealms/Issues#4]
The game over message says 'Game Over!' and underneath it says 'Kyoal wins!'. It should be 'purple wins!'
http://prntscr.com/crfoe6

**Comment by tylerCain** [comment]
This is only when a user double caps, or completes all objectives. I want other opinions @Palmidence

**Comment by Palmidence** [comment]
Let it be just purple

**Comment by tylerCain** [comment]
Fixed.
