### ISSUE TITLE
Fix Fort Aqua's monuments 

### ISSUE THREAD

**Issue by Kyoal** [EquinoxRealms/Issues#6]
The scoreboard does not show for destroy the monument maps. When you break the whole monument, nothing happens and there is no effect on the game. A message saying that the user has broken the monument does not show due to the monument being broken not registering.

**Comment by Tazzy** [comment]
why are you assigning me

**Comment by Kyoal** [comment]
It could be a plugin issue

**Comment by Kyoal** [comment]
@prodigy4532 Check override slack please and see if you can fix the issue.

**Comment by Prodigy4532** [comment]
I need the map to fix this

**Comment by tylerCain** [comment]
XML fixed.
